name: Generate PDF and Upload Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/extra:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate PDF from Markdown
        run: pandoc cv.md -o cv.pdf --pdf-engine=pdflatex --template=template.latex

      - name: Save PDF for next job
        uses: actions/upload-artifact@v4.0.0
        with:
          name: cv-pdf
          path: cv.pdf

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PDF from build
        uses: actions/download-artifact@v4.0.0
        with:
          name: cv-pdf

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Upload PDF to GitHub Release
        run: |
          gh release upload latest-cv cv.pdf --clobber || \
          (gh release create latest-cv --title "Latest CV" --notes "Latest version of the CV" && \
           gh release upload latest-cv cv.pdf --clobber)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
